### ISSUE TITLE
http://docs.piston.rs/conrod/conrod/ Is broken

### ISSUE THREAD

**Issue by JGHFunRun** [PistonDevelopers/conrod#1313]
I'm trying to learn Conrod, and I though I would vist http://docs.piston.rs/ to find some examples. When I clicked to top link that said `Conrod`, it gave 404.

**Comment by bvssvni** [comment]
We are using https://docs.rs/conrod/0.61.1/conrod/ now. Where did you find the broken link?

**Comment by shanehandley** [comment]
See also: #1306

**Comment by JGHFunRun** [comment]
@bvssvni That would explain it. I think it's fixed now.

**Comment by malaire** [comment]
Most links at https://crates.io/crates/conrod are 404, for example "The Guide", "What is Conrod?", etc.

**Comment by sbrl** [comment]
Nope, it is not fixed. I have just run into this when I clicked the "Documentation" link on crates.io in a last-ditch attempt to find an actually useful tutorial (it seems that the next chapter of the tutorial which  need to read isn't written yet :-/).

**Comment by alberdingk-thijm** [comment]
Per the build logs [here](https://docs.rs/crate/conrod_core/0.68.0/builds/195775), this is caused by the `xcb` crate, which I'm guessing was pulled in for the new `TextBox` copy-paste functionality in 0.68. `xcb` has a few dependencies that are probably not installed on docs.rs.

My package `conrod_prompt` (see #1299) is also not building due to the same issue. I was able to resolve this for a separate project at least on GitLab by adding a few prerequisites:

```yaml
before_script:   
    - apt-get update -yqq   
    - apt-get install -yqq --no-install-recommends build-essential   
    - apt-get install -yqq xcb libxcb-shape0-dev libxcb-xfixes0-dev libx11-xcb-dev 
  
script:
     - rustc --version && cargo --version  
    - cargo test --all --verbose
```

**Comment by alberdingk-thijm** [comment]
Related: https://github.com/rust-lang/docs.rs/issues/471#issuecomment-551892709

**Comment by alberdingk-thijm** [comment]
`copypasta` has now been [bumped to 0.6.1](https://github.com/jwilm/alacritty/pull/3024), so all existing dependencies no longer rely on `xcb` 0.8.2. The docs should work on the next docs.rs build.

**Comment by alvinhochun** [comment]
I believe this is now irrelevant.
