### ISSUE TITLE
Line is not drawn

### ISSUE THREAD

**Issue by andresv** [PistonDevelopers/conrod#692]
Mac OS X 10.11.3
Conrod 0.31.3

Here is following snippet:

```Rust
#[macro_use] extern crate conrod;
extern crate find_folder;
extern crate piston_window;

use conrod::{
    Labelable,
    Positionable,
    Sizeable,
    Colorable,
    Frameable,
    Rectangle,
    FramedRectangle,
    FramedRectangleStyle,
    Place,
    Theme,
    Text,
    TextBox,
    Line,
    LineStyle,
    Circle,
    ShapeStyle,
    Ui,
    Widget
};

use conrod::color::{rgb, rgba};

use piston_window::{EventLoop, Glyphs, PistonWindow, UpdateEvent, WindowSettings};

fn main() {

    // Construct the window.
    let window: PistonWindow = WindowSettings::new("Garage Inc", [800, 480])
        .exit_on_esc(true).build().unwrap();

    // construct our `Ui`.
    let mut ui = {
        let assets = find_folder::Search::KidsThenParents(3, 5)
            .for_folder("assets").unwrap();
        let font_path = assets.join("fonts/NotoSans/NotoSans-Regular.ttf");
        let theme = Theme::default();
        let glyph_cache = Glyphs::new(&font_path, window.factory.borrow().clone());
        Ui::new(glyph_cache.unwrap(), theme)
    };

    let mut f1_state = false;

    // Poll events from the window.
    for event in window.ups(60) {
        ui.handle_event(&event);
        event.update(|_| ui.set_widgets(|ui| {
            // Create a background canvas upon which we'll place the button.
            // pad 5px from each side
            conrod::Canvas::new().pad(5.0).set(CANVAS, ui);

            // draw title
            Text::new("Garage Inc")
                .mid_top_of(CANVAS)
                .font_size(14)
                .color(rgb(0.2, 0.35, 0.45).plain_contrast())
                .set(TITLE, ui);

            // draw current time
            Text::new("22:01")
                .top_right_of(CANVAS)
                .font_size(16)
                .color(rgb(0.2, 0.35, 0.45).plain_contrast())
                .set(CLOCK, ui);

            // draw relay states
            // for i in 0..8 {
            //     Rectangle::outline([45.0, 45.0])
            //         .align_left_of(CANVAS)
            //         .set(RELAY + i, ui);
            //
            //     Text::new(&format!("Relay {:}", i)[..])
            //         .right_from(RELAY + i, 10.0)
            //         .align_middle_y_of(RELAY + i)
            //         .font_size(14)
            //         .color(rgb(0.2, 0.35, 0.45).plain_contrast())
            //         .set(RELAY_TEXT + i, ui);
            // }
            //
            // Text::new("23.1")
            //     .right_from(RELAY_TEXT + (0*2), 40.0)
            //     .font_size(72)
            //     .color(rgb(0.2, 0.35, 0.45).plain_contrast())
            //     .set(CURRENT_TEMP, ui);
            //
            // // Draw the button and increment `count` if pressed.
            // conrod::Button::new()
            //     .right_from(CURRENT_TEMP, 10.0)
            //     //.align_middle_y_of(CURRENT_TEMP)
            //     .w_h(60.0, 60.0)
            //     .label(&count.to_string())
            //     .react(|| count += 1)
            //     .set(SET_TEMP, ui);

            TextBox::new(&mut " HEATER".to_string())
                .font_size(16)
                .w_h(80.0, 120.0)
                .x_y(0.0, 90.0)
                .color(rgb(1.0, 0.65, 0.18))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .react(|_string: &mut String|{})
                .set(HEATER, ui);

            let (x, y, w, h) = ui.rect_of(HEATER).unwrap().x_y_w_h();
            Line::styled([x-w/2.-180., y+h/2.], [x-w/2., y+h/2.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE, ui);

            //let (x, y, w, h) = ui.rect_of(PIPE).unwrap().x_y_w_h();
            //println!("x {:} y {:}, w {:}, h {:}", x, y, w, h);
            //let (l, r, b, t) = ui.rect_of(PIPE).unwrap().l_r_b_t();
            //println!("l {:} r {:}, b {:}, t {:}", l, r, b, t);

            //let r = 25.0;
            // solid or outline
            //Circle::styled(r, ShapeStyle::fill_with(rgb(0.0, 0.8, 0.0)))
            // Circle::styled(r, ShapeStyle::outline_styled(LineStyle::new().thickness(2.0)))
            //     .x_y(x-w/2.-150.-r, y+h/2.)
            //     .set(FAN, ui);
            //
            // Text::new("F1")
            //     .middle_of(FAN)
            //     .font_size(24)
            //     .color(rgb(1.0, 1.0, 1.0))
            //     .set(FAN_TEXT, ui);

            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x-w/2.-180., y+h/2.)
                .w_h(50., 50.)
                .label("F1")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(F1_BUTTON, ui);

            let (x, y, w, h) = ui.rect_of(F1_BUTTON).unwrap().x_y_w_h();
            Line::styled([x, y-h/2.], [x, y-h/2.-25.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+1, ui);

            Text::new("PAINTING")
                .down_from(PIPE+1, -40.)
                .align_middle_x_of(PIPE+1)
                .font_size(16)
                .color(rgb(1.0, 1.0, 1.0))
                .set(PAINTING_TEXT, ui);

            // P1
            let (x, y, w, h) = ui.rect_of(PAINTING_TEXT).unwrap().x_y_w_h();
            let indicator_w = 60.0;
            let indicator_h = 60.0;
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-2.*indicator_w)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(P_RECT, ui);
            Text::new("P1")
                .x(x-2.*indicator_w)
                .y_place_on(P_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(P_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-2.*indicator_w)
                .down_from(P_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(P_TEMP_RECT, ui);
            Text::new("760")
                .x(x-2.*indicator_w)
                .y_place_on(P_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(P_TEMP_VALUE, ui);

            // T1
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-indicator_w/2. + 1.)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_RECT, ui);
            Text::new("T1")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_RECT, ui);
            Text::new("43")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_VALUE, ui);

            // T1 SET
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x+indicator_w/2.)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_RECT, ui);
            Text::new("SET")
                .x(x+indicator_w/2.)
                .y_place_on(SET_T_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x+indicator_w/2.)
                .down_from(SET_T_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_TEMP_RECT, ui);
            Text::new("65")
                .x(x+indicator_w/2.)
                .y_place_on(SET_T_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(0.8, 0.0, 0.0))
                .set(SET_T_TEMP_VALUE, ui);

            // T1 +- buttons
            let (x, y, w, h) = ui.rect_of(SET_T_RECT).unwrap().x_y_w_h();
            let (l, r, b, t) = ui.rect_of(SET_T_RECT).unwrap().l_r_b_t();
            let t1_plus_h = (indicator_h + indicator_h/2.)/2.;
            let t1_plus_w = (indicator_h + indicator_h/2.)/2.;
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + t1_plus_w/2. - 1., t-t1_plus_h/2.)
                .w_h(t1_plus_w, t1_plus_h)
                .label("+")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .large_font(ui)
                .set(SET_T1_PLUS, ui);
            let (l, r, b, t) = ui.rect_of(SET_T_TEMP_RECT).unwrap().l_r_b_t();
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + t1_plus_w/2. - 1., b+t1_plus_h/2.)
                .w_h(t1_plus_w, t1_plus_h)
                .label("-")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .large_font(ui)
                .set(SET_T1_MINUS, ui);

            // T2
            let (x, _, _, _) = ui.rect_of(PAINTING_TEXT).unwrap().x_y_w_h();
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_TEMP_VALUE, 40.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_RECT + 1, ui);
            Text::new("T2")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_RECT + 1, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEXT + 1, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_RECT + 1, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_RECT + 1, ui);
            Text::new("30")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_TEMP_RECT + 1, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_VALUE + 1, ui);

            // pipe from painting chamber
            let (x, y, w, h) = ui.rect_of(T_TEMP_RECT + 1).unwrap().x_y_w_h();
            Line::styled([x+w/2., y], [x+w/2. + 50., y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+2, ui);

            // V1 valve
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + 50. + 50./2., y)
                .w_h(50., 50.)
                .label("V1")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(V1_BUTTON, ui);

            let pipelen = 45.0;
            let (x, y, w, h) = ui.rect_of(V1_BUTTON).unwrap().x_y_w_h();
            Line::styled([x+w/2., y], [x+w/2. + pipelen, y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+3, ui);

            // F2
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x+w/2. + pipelen + 50./2., y)
                .w_h(50., 50.)
                .label("F2")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(F2_BUTTON, ui);

            // V2
            let heater_x = ui.rect_of(HEATER).unwrap().x();
            let heater_y = ui.rect_of(HEATER).unwrap().y();
            let f2_b = ui.rect_of(F2_BUTTON).unwrap().bottom();
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(heater_x, f2_b-50./2.)
                .label("V2")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(V2_BUTTON, ui);

            // pipe from heater to V2
            // let heater_b = ui.rect_of(HEATER).unwrap().bottom();
            // let v2_top = ui.rect_of(V2_BUTTON).unwrap().top();
            // Line::styled([heater_x, heater_b], [heater_x, v2_top], LineStyle::new())
            //     .thickness(4.0)
            //     .set(PIPE+4, ui);

            let f2_x = ui.rect_of(F2_BUTTON).unwrap().x();
            let f2_y = ui.rect_of(F2_BUTTON).unwrap().y();
            let f2_w = ui.rect_of(F2_BUTTON).unwrap().w();
            //Line::styled([f2_x + f2_w/2., f2_y], [heater_x, f2_y], LineStyle::new())
            Line::styled([100., 100.], [100. + 50., 100.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+4, ui);

            Line::styled([100., 200.], [100. + 50., 200.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+5, ui);

        }));
        event.draw_2d(|c, g| ui.draw_if_changed(c, g));
    }

}

widget_ids! {
    CANVAS,
    TITLE,
    CLOCK,

    HEATER,
    PIPE with 6,
    F1_BUTTON,
    PAINTING_TEXT,

    P_RECT,
    P_TEXT,
    P_TEMP_RECT,
    P_TEMP_VALUE,

    T_RECT with 2,
    T_TEXT with 2,
    T_TEMP_RECT with 2,
    T_TEMP_VALUE with 2,

    SET_T_RECT,
    SET_T_TEXT,
    SET_T_TEMP_RECT,
    SET_T_TEMP_VALUE,

    SET_T1_PLUS,
    SET_T1_MINUS,

    V1_BUTTON,
    F2_BUTTON,
    V2_BUTTON,
}

```

And it draws this:
![screenshot 2016-02-14 22 18 59](https://cloud.githubusercontent.com/assets/809232/13036176/fb4cc538-d368-11e5-8c1b-c2fd433935e8.jpg)

Notice that there is single line near `Heater`, however actually there should be 2 lines:

```Rust
Line::styled([100., 100.], [100. + 50., 100.], LineStyle::new())
    .thickness(4.0)
    .set(PIPE+4, ui);

Line::styled([100., 200.], [100. + 50., 200.], LineStyle::new())
    .thickness(4.0)
    .set(PIPE+5, ui);
```

The strange thing is that they are drawn if I remove `V2_BUTTON`

```Rust
            // conrod::Button::new()
            //     .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
            //     .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
            //     .x_y(heater_x, f2_b-50./2.)
            //     .label("V2")
            //     .frame_color(rgb(1.0, 1.0, 1.0))
            //     .label_color(rgb(1.0, 1.0, 1.0))
            //     .react(|| f1_state = !f1_state)
            //     .medium_font(ui)
            //     .set(V2_BUTTON, ui);
```

Then it will become:

![screenshot 2016-02-14 22 23 57](https://cloud.githubusercontent.com/assets/809232/13036207/a909e3a4-d369-11e5-96c7-1a8213bde865.jpg)

**Comment by andresv** [comment]
Hmm and it works if it is drawn in this order

1. line
1. button
1. line

```Rust
            Line::styled([100., 100.], [100. + 50., 100.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+4, ui);
                
            // V2
            let heater_x = ui.rect_of(HEATER).unwrap().x();
            let heater_y = ui.rect_of(HEATER).unwrap().y();
            let f2_b = ui.rect_of(F2_BUTTON).unwrap().bottom();
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(heater_x, f2_b-50./2.)
                .label("V2")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(V2_BUTTON, ui);

            Line::styled([100., 200.], [100. + 50., 200.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+5, ui);
```

**Comment by mitchmindtree** [comment]
@andresv Hey, it sounds like you might benefit from checking out the `Line` docs [here](http://docs.piston.rs/conrod/conrod/struct.Line.html). `Line` has a few different constructors depending on the way that you wish to position them, whether you want to style it etc.

| default style (specified by theme) | use custom style for this line |
|-----------------|----------|
| [new](http://docs.piston.rs/conrod/conrod/struct.Line.html#method.abs) | [styled](http://docs.piston.rs/conrod/conrod/struct.Line.html#method.styled) |
| [centred](http://docs.piston.rs/conrod/conrod/struct.Line.html#method.centred) | [centred_styled](http://docs.piston.rs/conrod/conrod/struct.Line.html#method.centred_styled) |
| [abs](http://docs.piston.rs/conrod/conrod/struct.Line.html#method.abs) | [abs_styled](http://docs.piston.rs/conrod/conrod/struct.Line.html#method.abs_styled) |

Both [`Line::centred`](http://docs.piston.rs/conrod/conrod/struct.Line.html#method.centred) and [`Line::abs`](http://docs.piston.rs/conrod/conrod/struct.Line.html#method.abs) are probably the most useful. `centred` is useful when you just want to position it relative to something, i.e. `.right_of(FOO)` - it will automatically shift the two given points so that they retain their shape but are in the position specified. `abs` on the other hand will automatically set the `xy` coordinates for the `Line` as the middle of the two points with which you construct it. By the looks of it, the `Line::abs` constructor is what you want (rather than `Line::styled`).

Currently, the `Line` isn't automatically positioned when using `Line::new` or `Line::styled` - it will fall back to a default position (specified by the `Theme`) if one isn't given specifically, so conrod will think that the `Line` is wherever that position is, while still drawing the points at the place you specified. This is definitely bug-inducing behaviour (as you've demonstrated!) so perhaps it might be best to make the `Line`'s `new` and `styled` constructors private (especially considering `abs` and `centred` probably cover all use cases)?

Let me know if changing to using `Line::abs` fixes things for you. Also, thanks a lot for posting these issues, the feedback is highly appreciated :+1:  The GUI is looking really cool btw!

**Comment by andresv** [comment]
I actually checked the Line docs and just tried with `Line::new` first and it kind of worked as expected for me. So I got a false impression from that and did not realise that `Line::abs` suits my needs better.

I started to change `Line::styled` to `Line::abs_styled` (`styled` because soon i will check how to add arrows) however there seems to be some more going on with lines and it does not quite work as expected.

So following snippet

```Rust
#[macro_use] extern crate conrod;
extern crate find_folder;
extern crate piston_window;

use conrod::{
    Labelable,
    Positionable,
    Sizeable,
    Colorable,
    Frameable,
    Rectangle,
    FramedRectangle,
    FramedRectangleStyle,
    Place,
    Theme,
    Text,
    TextBox,
    Line,
    LineStyle,
    Circle,
    ShapeStyle,
    Ui,
    Widget
};

use conrod::color::{rgb, rgba};

use piston_window::{EventLoop, Glyphs, PistonWindow, UpdateEvent, WindowSettings};

fn main() {

    // Construct the window.
    let window: PistonWindow = WindowSettings::new("Garage Inc", [800, 480])
        .exit_on_esc(true).build().unwrap();

    // construct our `Ui`.
    let mut ui = {
        let assets = find_folder::Search::KidsThenParents(3, 5)
            .for_folder("assets").unwrap();
        let font_path = assets.join("fonts/NotoSans/NotoSans-Regular.ttf");
        let theme = Theme::default();
        let glyph_cache = Glyphs::new(&font_path, window.factory.borrow().clone());
        Ui::new(glyph_cache.unwrap(), theme)
    };

    let mut f1_state = false;

    // Poll events from the window.
    for event in window.ups(60) {
        ui.handle_event(&event);
        event.update(|_| ui.set_widgets(|ui| {
            // Create a background canvas upon which we'll place the button.
            // pad 5px from each side
            conrod::Canvas::new().pad(5.0).set(CANVAS, ui);

            // draw title
            Text::new("Garage Inc")
                .mid_top_of(CANVAS)
                .font_size(14)
                .color(rgb(0.2, 0.35, 0.45).plain_contrast())
                .set(TITLE, ui);

            // draw current time
            Text::new("22:01")
                .top_right_of(CANVAS)
                .font_size(16)
                .color(rgb(0.2, 0.35, 0.45).plain_contrast())
                .set(CLOCK, ui);

            TextBox::new(&mut " HEATER".to_string())
                .font_size(16)
                .w_h(80.0, 120.0)
                .x_y(0.0, 90.0)
                .color(rgb(1.0, 0.65, 0.18))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .react(|_string: &mut String|{})
                .set(HEATER, ui);

            let (x, y, w, h) = ui.rect_of(HEATER).unwrap().x_y_w_h();
            Line::abs_styled([x-w/2.-180., y+h/2.], [x-w/2., y+h/2.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE, ui);

            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x-w/2.-180., y+h/2.)
                .w_h(50., 50.)
                .label("F1")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(F1_BUTTON, ui);

            let (x, y, w, h) = ui.rect_of(F1_BUTTON).unwrap().x_y_w_h();
            Line::abs_styled([x, y-h/2.], [x, y-h/2.-25.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+1, ui);

            Text::new("PAINTING")
                .down_from(F1_BUTTON, 40.)
                .align_middle_x_of(PIPE+1)
                .font_size(16)
                .color(rgb(1.0, 1.0, 1.0))
                .set(PAINTING_TEXT, ui);

            // P1
            let (x, y, w, h) = ui.rect_of(PAINTING_TEXT).unwrap().x_y_w_h();
            let indicator_w = 60.0;
            let indicator_h = 60.0;
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-2.*indicator_w)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(P_RECT, ui);
            Text::new("P1")
                .x(x-2.*indicator_w)
                .y_place_on(P_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(P_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-2.*indicator_w)
                .down_from(P_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(P_TEMP_RECT, ui);
            Text::new("760")
                .x(x-2.*indicator_w)
                .y_place_on(P_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(P_TEMP_VALUE, ui);

            // T1
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-indicator_w/2. + 1.)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_RECT, ui);
            Text::new("T1")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_RECT, ui);
            Text::new("43")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_VALUE, ui);

            // T1 SET
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x+indicator_w/2.)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_RECT, ui);
            Text::new("SET")
                .x(x+indicator_w/2.)
                .y_place_on(SET_T_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x+indicator_w/2.)
                .down_from(SET_T_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_TEMP_RECT, ui);
            Text::new("65")
                .x(x+indicator_w/2.)
                .y_place_on(SET_T_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(0.8, 0.0, 0.0))
                .set(SET_T_TEMP_VALUE, ui);

            // T1 +- buttons
            let (x, y, w, h) = ui.rect_of(SET_T_RECT).unwrap().x_y_w_h();
            let (l, r, b, t) = ui.rect_of(SET_T_RECT).unwrap().l_r_b_t();
            let t1_plus_h = (indicator_h + indicator_h/2.)/2.;
            let t1_plus_w = (indicator_h + indicator_h/2.)/2.;
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + t1_plus_w/2. - 1., t-t1_plus_h/2.)
                .w_h(t1_plus_w, t1_plus_h)
                .label("+")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .large_font(ui)
                .set(SET_T1_PLUS, ui);
            let (l, r, b, t) = ui.rect_of(SET_T_TEMP_RECT).unwrap().l_r_b_t();
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + t1_plus_w/2. - 1., b+t1_plus_h/2.)
                .w_h(t1_plus_w, t1_plus_h)
                .label("-")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .large_font(ui)
                .set(SET_T1_MINUS, ui);

            // T2
            let (x, _, _, _) = ui.rect_of(PAINTING_TEXT).unwrap().x_y_w_h();
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_TEMP_VALUE, 40.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_RECT + 1, ui);
            Text::new("T2")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_RECT + 1, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEXT + 1, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_RECT + 1, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_RECT + 1, ui);
            Text::new("30")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_TEMP_RECT + 1, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_VALUE + 1, ui);

            // pipe from painting chamber
            let (x, y, w, h) = ui.rect_of(T_TEMP_RECT + 1).unwrap().x_y_w_h();
            Line::abs_styled([x+w/2., y], [x+w/2. + 50., y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+2, ui);

            // V1 valve
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + 50. + 50./2., y)
                .w_h(50., 50.)
                .label("V1")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(V1_BUTTON, ui);

            let pipelen = 45.0;
            let (x, y, w, h) = ui.rect_of(V1_BUTTON).unwrap().x_y_w_h();
            Line::abs_styled([x+w/2., y], [x+w/2. + pipelen, y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+3, ui);

            // F2
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x+w/2. + pipelen + 50./2., y)
                .w_h(50., 50.)
                .label("F2")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(F2_BUTTON, ui);

            // pipe from F2 to heater_x that will intersect with another pipe later
            let heater_x = ui.rect_of(HEATER).unwrap().x();
            let f2_x = ui.rect_of(F2_BUTTON).unwrap().x();
            let f2_y = ui.rect_of(F2_BUTTON).unwrap().y();
            let f2_w = ui.rect_of(F2_BUTTON).unwrap().w();
            Line::abs_styled([f2_x + f2_w/2., f2_y], [heater_x, f2_y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+4, ui);

            // V2
            let f2_b = ui.rect_of(F2_BUTTON).unwrap().bottom();
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(heater_x, f2_b-50./2.)
                .label("V2")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(V2_BUTTON, ui);

            // pipe from heater to V2
            // let heater_b = ui.rect_of(HEATER).unwrap().bottom();
            // let v2_top = ui.rect_of(V2_BUTTON).unwrap().top();
            // Line::styled([heater_x, heater_b], [heater_x, v2_top], LineStyle::new())
            //     .thickness(4.0)
            //     .set(PIPE+5, ui);

            // Text::new("OUTSIDE")
            //     .down_from(V2_BUTTON, 20.)
            //     .align_middle_x_of(V2_BUTTON)
            //     .font_size(16)
            //     .color(rgb(1.0, 1.0, 1.0))
            //     .set(OUTSIDE_TEXT, ui);

            //
            // let (x, y, w, h) = ui.rect_of(HEATER).unwrap().x_y_w_h();
            // Line::styled([x-w/2.+180., y+h/2.], [x-w/2., y+h/2.], LineStyle::new())
            //     .thickness(4.0)
            //     .set(PIPE+6, ui);

        }));
        event.draw_2d(|c, g| ui.draw_if_changed(c, g));
    }

}

widget_ids! {
    CANVAS,
    TITLE,
    CLOCK,

    HEATER,
    PIPE with 7,
    F1_BUTTON,
    PAINTING_TEXT,

    P_RECT,
    P_TEXT,
    P_TEMP_RECT,
    P_TEMP_VALUE,

    T_RECT with 2,
    T_TEXT with 2,
    T_TEMP_RECT with 2,
    T_TEMP_VALUE with 2,

    SET_T_RECT,
    SET_T_TEXT,
    SET_T_TEMP_RECT,
    SET_T_TEMP_VALUE,

    SET_T1_PLUS,
    SET_T1_MINUS,

    V1_BUTTON,
    F2_BUTTON,
    V2_BUTTON,
    OUTSIDE_TEXT,
}
```

..produces this:

![screenshot 2016-02-15 22 59 42](https://cloud.githubusercontent.com/assets/809232/13060122/d65edc82-d437-11e5-9f80-c42334195a75.jpg)

Now only label is drawn from `V2_BUTTON` and `PIPE+4` itself is not visible either.

**Comment by mitchmindtree** [comment]
> I actually checked the Line docs and just tried with Line::new first and it kind of worked as expected for me. So I got a false impression from that and did not realise that Line::abs suits my needs better.

Sorry about this!

> Now only label is drawn from V2_BUTTON and PIPE+4 itself is not visible either.

Hopefully I'll get a chance to take a closer look at your code later on tonight.

**Comment by andresv** [comment]
@mitchmindtree what do you think, is it bug in library or am I using it incorrectly?

**Comment by mitchmindtree** [comment]
@andresv I just fixed a parent inference bug at #701 which might be related. It's been merged, but hasn't been published yet (waiting on another couple pending PRs before publishing).

**Comment by andresv** [comment]
@mitchmindtree I tried with the latest version.

Replaced:
```
[dependencies]
conrod = "*"
```
With
```
[dependencies.conrod]
git = "https://github.com/PistonDevelopers/conrod.git"
```

However it is still the same.

**Comment by andresv** [comment]
Hi,

I just tried again. However the problem is still there.
Here is the code compatible with 0.37.2.

```Rust
#[macro_use] extern crate conrod;
extern crate find_folder;
extern crate piston_window;

use conrod::{
    Labelable,
    Positionable,
    Sizeable,
    Colorable,
    Frameable,
    Rectangle,
    FramedRectangle,
    FramedRectangleStyle,
    Place,
    Theme,
    Text,
    TextBox,
    Line,
    LineStyle,
    Circle,
    ShapeStyle,
    Widget
};

use conrod::color::{rgb, rgba};

use piston_window::{EventLoop, Glyphs, PistonWindow, UpdateEvent, WindowSettings};

type Backend = (<piston_window::G2d<'static> as conrod::Graphics>::Texture, Glyphs);
type Ui = conrod::Ui<Backend>;
type UiCell<'a> = conrod::UiCell<'a, Backend>;

fn main() {

    // Construct the window.
    let mut window: PistonWindow = WindowSettings::new("Garage Inc", [800, 480])
        .exit_on_esc(true).build().unwrap();

    // construct our `Ui`.
    let mut ui = {
        let assets = find_folder::Search::KidsThenParents(3, 5)
            .for_folder("assets").unwrap();
        let font_path = assets.join("fonts/NotoSans/NotoSans-Regular.ttf");
        let theme = Theme::default();
        let glyph_cache = Glyphs::new(&font_path, window.factory.clone());
        Ui::new(glyph_cache.unwrap(), theme)
    };

    let mut f1_state = false;

    window.set_ups(60);
    // Poll events from the window.
    while let Some(event) = window.next() {
        ui.handle_event(event.clone());
        event.update(|_| ui.set_widgets(|ref mut ui| {
            // Create a background canvas upon which we'll place the button.
            // pad 5px from each side
            conrod::Canvas::new().pad(5.0).set(CANVAS, ui);

            // draw title
            Text::new("Garage Inc")
                .mid_top_of(CANVAS)
                .font_size(14)
                .color(rgb(0.2, 0.35, 0.45).plain_contrast())
                .set(TITLE, ui);

            // draw current time
            Text::new("22:01")
                .top_right_of(CANVAS)
                .font_size(16)
                .color(rgb(0.2, 0.35, 0.45).plain_contrast())
                .set(CLOCK, ui);

            TextBox::new(&mut " HEATER".to_string())
                .font_size(16)
                .w_h(80.0, 120.0)
                .x_y(0.0, 90.0)
                .color(rgb(1.0, 0.65, 0.18))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .react(|_string: &mut String|{})
                .set(HEATER, ui);

            let (x, y, w, h) = ui.rect_of(HEATER).unwrap().x_y_w_h();
            Line::abs_styled([x-w/2.-180., y+h/2.], [x-w/2., y+h/2.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE, ui);

            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x-w/2.-180., y+h/2.)
                .w_h(50., 50.)
                .label("F1")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(F1_BUTTON, ui);

            let (x, y, w, h) = ui.rect_of(F1_BUTTON).unwrap().x_y_w_h();
            Line::abs_styled([x, y-h/2.], [x, y-h/2.-25.], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+1, ui);

            Text::new("PAINTING")
                .down_from(F1_BUTTON, 40.)
                .align_middle_x_of(PIPE+1)
                .font_size(16)
                .color(rgb(1.0, 1.0, 1.0))
                .set(PAINTING_TEXT, ui);

            // P1
            let (x, y, w, h) = ui.rect_of(PAINTING_TEXT).unwrap().x_y_w_h();
            let indicator_w = 60.0;
            let indicator_h = 60.0;
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-2.*indicator_w)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(P_RECT, ui);
            Text::new("P1")
                .x(x-2.*indicator_w)
                .y_place_on(P_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(P_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-2.*indicator_w)
                .down_from(P_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(P_TEMP_RECT, ui);
            Text::new("760")
                .x(x-2.*indicator_w)
                .y_place_on(P_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(P_TEMP_VALUE, ui);

            // T1
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-indicator_w/2. + 1.)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_RECT, ui);
            Text::new("T1")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_RECT, ui);
            Text::new("43")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_VALUE, ui);

            // T1 SET
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x+indicator_w/2.)
                .down_from(PAINTING_TEXT, 20.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_RECT, ui);
            Text::new("SET")
                .x(x+indicator_w/2.)
                .y_place_on(SET_T_RECT, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_TEXT, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x+indicator_w/2.)
                .down_from(SET_T_RECT, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(SET_T_TEMP_RECT, ui);
            Text::new("65")
                .x(x+indicator_w/2.)
                .y_place_on(SET_T_TEMP_RECT, Place::Middle)
                .font_size(32)
                .color(rgb(0.8, 0.0, 0.0))
                .set(SET_T_TEMP_VALUE, ui);

            // T1 +- buttons
            let (x, y, w, h) = ui.rect_of(SET_T_RECT).unwrap().x_y_w_h();
            let (l, r, b, t) = ui.rect_of(SET_T_RECT).unwrap().l_r_b_t();
            let t1_plus_h = (indicator_h + indicator_h/2.)/2.;
            let t1_plus_w = (indicator_h + indicator_h/2.)/2.;
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + t1_plus_w/2. - 1., t-t1_plus_h/2.)
                .w_h(t1_plus_w, t1_plus_h)
                .label("+")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .large_font(ui)
                .set(SET_T1_PLUS, ui);
            let (l, r, b, t) = ui.rect_of(SET_T_TEMP_RECT).unwrap().l_r_b_t();
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + t1_plus_w/2. - 1., b+t1_plus_h/2.)
                .w_h(t1_plus_w, t1_plus_h)
                .label("-")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .large_font(ui)
                .set(SET_T1_MINUS, ui);

            // T2
            let (x, _, _, _) = ui.rect_of(PAINTING_TEXT).unwrap().x_y_w_h();
            FramedRectangle::new([indicator_w, indicator_h/2.])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_TEMP_VALUE, 40.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_RECT + 1, ui);
            Text::new("T2")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_RECT + 1, Place::Middle)
                .font_size(14)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEXT + 1, ui);
            FramedRectangle::new([indicator_w, indicator_h])
                .x(x-indicator_w/2. + 1.)
                .down_from(T_RECT + 1, -1.)
                .color(rgb(0.0, 0.0, 0.0))
                .frame_color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_RECT + 1, ui);
            Text::new("30")
                .x(x-indicator_w/2. + 1.)
                .y_place_on(T_TEMP_RECT + 1, Place::Middle)
                .font_size(32)
                .color(rgb(1.0, 1.0, 1.0))
                .set(T_TEMP_VALUE + 1, ui);

            // pipe from painting chamber
            let (x, y, w, h) = ui.rect_of(T_TEMP_RECT + 1).unwrap().x_y_w_h();
            Line::abs_styled([x+w/2., y], [x+w/2. + 50., y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+2, ui);

            // V1 valve
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x + w/2. + 50. + 50./2., y)
                .w_h(50., 50.)
                .label("V1")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(V1_BUTTON, ui);

            let pipelen = 45.0;
            let (x, y, w, h) = ui.rect_of(V1_BUTTON).unwrap().x_y_w_h();
            Line::abs_styled([x+w/2., y], [x+w/2. + pipelen, y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+3, ui);

            // F2
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(x+w/2. + pipelen + 50./2., y)
                .w_h(50., 50.)
                .label("F2")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(F2_BUTTON, ui);

            // pipe from F2 to heater_x that will intersect with another pipe later
            let heater_x = ui.rect_of(HEATER).unwrap().x();
            let f2_x = ui.rect_of(F2_BUTTON).unwrap().x();
            let f2_y = ui.rect_of(F2_BUTTON).unwrap().y();
            let f2_w = ui.rect_of(F2_BUTTON).unwrap().w();
            Line::abs_styled([f2_x + f2_w/2., f2_y], [heater_x, f2_y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+4, ui);

            // V2
            let f2_b = ui.rect_of(F2_BUTTON).unwrap().bottom();
            conrod::Button::new()
                .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
                .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
                .x_y(heater_x, f2_b-50./2.)
                .label("V2")
                .frame_color(rgb(1.0, 1.0, 1.0))
                .label_color(rgb(1.0, 1.0, 1.0))
                .react(|| f1_state = !f1_state)
                .medium_font(ui)
                .set(V2_BUTTON, ui);

            // pipe from heater to V2
            // let heater_b = ui.rect_of(HEATER).unwrap().bottom();
            // let v2_top = ui.rect_of(V2_BUTTON).unwrap().top();
            // Line::abs_styled([heater_x, heater_b], [heater_x, v2_top], LineStyle::new())
            //     .thickness(4.0)
            //     .set(PIPE+5, ui);
            //
            // Text::new("OUTSIDE")
            //     .down_from(V2_BUTTON, 20.)
            //     .align_middle_x_of(V2_BUTTON)
            //     .font_size(16)
            //     .color(rgb(1.0, 1.0, 1.0))
            //     .set(OUTSIDE_TEXT, ui);


            // let (x, y, w, h) = ui.rect_of(HEATER).unwrap().x_y_w_h();
            // Line::abs_styled([x-w/2.+180., y+h/2.], [x-w/2., y+h/2.], LineStyle::new())
            //     .thickness(4.0)
            //     .set(PIPE+6, ui);

        }));
        window.draw_2d(&event, |c, g| ui.draw_if_changed(c, g));
    }

}

widget_ids! {
    CANVAS,
    TITLE,
    CLOCK,

    HEATER,
    PIPE with 7,
    F1_BUTTON,
    PAINTING_TEXT,

    P_RECT,
    P_TEXT,
    P_TEMP_RECT,
    P_TEMP_VALUE,

    T_RECT with 2,
    T_TEXT with 2,
    T_TEMP_RECT with 2,
    T_TEMP_VALUE with 2,

    SET_T_RECT,
    SET_T_TEXT,
    SET_T_TEMP_RECT,
    SET_T_TEMP_VALUE,

    SET_T1_PLUS,
    SET_T1_MINUS,

    V1_BUTTON,
    F2_BUTTON,
    V2_BUTTON,
    OUTSIDE_TEXT,
}
```

It produces following.
![screenshot 2016-07-21 13 58 41](https://cloud.githubusercontent.com/assets/809232/17020628/6163202a-4f4b-11e6-84b0-f958de59f7fc.jpg)

Notice that bottom "V2" should be also actually button, however for some reason it is drawn incorrectly.
It can be fixed by removing those lines that draw a line from "F2" button.

```Rust
Line::abs_styled([f2_x + f2_w/2., f2_y], [heater_x, f2_y], LineStyle::new())
                .thickness(4.0)
                .set(PIPE+4, ui);
```

After that "V2" button is drawn correctly.

![screenshot 2016-07-21 14 02 33](https://cloud.githubusercontent.com/assets/809232/17020719/d588074a-4f4b-11e6-95a3-3dfaaa49b92b.jpg)

Maybe I am doing something stupid. Could you just try it on your machine.

PS: I am using stable Rust 1.10.0 on Mac OS X 10.11.5.

**Comment by mitchmindtree** [comment]
The issue with the "V2" button is that you do not specify its dimensions. It works when you remove the `Line` because the width and height is inferred from the previous widget if none are given explicitly or if there are no defaults set in the `Theme`. A horizontal line's height is zero, so that `Button` infers `0.0` as its height and is not displayed as a result.

Seeing as most of your buttons have many of the same properties, why not abstract the common stuff into a function? i.e.

```rust
fn new_button<'a, F>() -> conrod::Button<'a, F>
    where F: FnOnce(),
{
    conrod::Button::new()
        .w_h(50.0, 50.0)
        .frame_color(conrod::color::WHITE)
        .label_color(conrod::color::WHITE)
}
```

This would shorten your button code to look like this:

```rust
new_button()
    .and_if(f1_state, |button| button.color(rgb(0.0, 0.0, 0.0)))
    .and_if(!f1_state, |button| button.color(rgb(0.0, 0.7, 0.0)))
    .x_y(heater_x, f2_b-50./2.)
    .label("V2")
    .react(|| f1_state = !f1_state)
    .medium_font(ui)
    .set(V2_BUTTON, ui);
```

This way, there's less code to write and less of a chance you'll make mistakes like forgetting to duplicate lines.

Also, I notice that you use the `Line::abs_styled` constructor in most places where you use `Line`s. This is normally only necessary if you want to construct a `Line` with some pre-existing `LineStyle` instance. Most of your use-cases that look like this
```rust
Line::abs_styled(a, b, LineStyle::new())
```
could probably be changed to this:
```rust
Line::abs(a, b)
```

Hope this helps!

**Comment by andresv** [comment]
Yes that did the trick. I will close it.
