### ISSUE TITLE
Can't compile example

### ISSUE THREAD

**Issue by Paluth** [PistonDevelopers/conrod#962]
I extracted one of the examples into its own project, however it doesn't compile. If i compile it though conrod it compiles just fine with: cargo run --features "winit glium" --example text. But the attached project gives errors related to wayland. Is this a bug or something?
[test.tar.gz](https://github.com/PistonDevelopers/conrod/files/850701/test.tar.gz)

**Comment by daboross** [comment]
Your Cargo.lock seems to have `wayland-window` v0.4.5, which had a bug and has now been yanked from crates.io. Using `cargo update` to bring the version down to v0.4.4 should fix that.

One thing to note is that after that, you also want to bring the `assets` directory into your project, as the examples depend on the font files in there (and will error with a very.... generic result error).

**Comment by Paluth** [comment]
After running cargo update the project still doesn't compile. 
```error: aborting due to 185 previous errors

error: Could not compile `wayland-client`.  ```

**Comment by daboross** [comment]
Hm, ok. The new test.tar.gz you uploaded builds correctly for me with rustc 1.16.0, so I think it might be a more specific issue than that.

Could you possibly upload a full build log and the output of `rustc --version`?

**Comment by Paluth** [comment]
Hi, this morning it worked somehow. My cargo lock was apparently corrupted again:

```
cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Removing wayland-client v0.9.0
    Updating wayland-kbd v0.8.1 -> v0.8.0
    Removing wayland-scanner v0.9.0
    Removing wayland-sys v0.9.0
    Updating wayland-window v0.5.1 -> v0.5.0
```

Any ideia why this corruption occurs? I'm on a ubunto virtualbox, with rust 1.16.

**Comment by Paluth** [comment]
Also this a bug in this demo. The middle column text doesn't render correctly. After you mouse over the window, it fixes it self.

**Comment by daboross** [comment]
I'm not sure about Cargo.toml "corrupting" - it shouldn't change at all unless you use `cargo update` or modify `Cargo.toml`. As for where the wayland-client came from, I believe it was a published version which the author then yanked after it was shown to be bugged.

I haven't seen the bug in the text demonstration, I am seeing that, it's somewhat strange. I believe this is due to the example framework not rendering enough times initially in conrod, but I could be wrong about that - best to let mindtree or another contributor have a say on the cause of that.

**Comment by Paluth** [comment]
Thanks for the help, maybe I will open another issue for the bug, but this one is resolved.
